version: '2'
services:
    scaffold-app:
        image: scaffold
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://scaffold-mysql:3306/scaffold?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    scaffold-mysql:
        extends:
            file: mysql.yml
            service: scaffold-mysql
